### ISSUE TITLE
New ansible galaxy release ?

### ISSUE THREAD

**Issue by juanluisbaptiste** [openmicroscopy/ansible-role-nfs-mount#7]
Hi,

I see there's a new release (1.3) tagged here that is not available at ansible galaxy, are you planning on updating the available release there ?

**Comment by sbesson** [comment]
Hi @juanluisbaptiste, the Galaxy role should be automatically updated on each tag. As far as I can see `1.3.0` is available on https://galaxy.ansible.com/ome/nfs_mount. Which error are you getting on your side when trying to download it?

**Comment by juanluisbaptiste** [comment]
Hi @sbesson , well on the galaxy site it says that the last version is 1.2:

![Screenshot_20201202_103815](https://user-images.githubusercontent.com/2113585/100894549-9aab9780-348a-11eb-852e-f7f7064435f8.png)

I have not looked further than that.. Also there is this warning at the top of the page:

_This item has been deprecated. We recommend that you take a look at one of these instead._

**Comment by sbesson** [comment]
@juanluisbaptiste I assume you are looking at https://galaxy.ansible.com/openmicroscopy/nfs-mount. All roles within this legacy organization have been deprecated and the recent versions are available under https://galaxy.ansible.com/ome instead with the Galaxy naming scheme using `_` rather than `-`.

I have also updated the repository link to use the correct URL

**Comment by juanluisbaptiste** [comment]
That's right, I got to the galaxy repo by clicking on the link here at github. I will switch to that one, thanks !!

**Comment by sbesson** [comment]
No worries, thanks for pointing that the repository URL was outdated. Closing this issue.
